### ISSUE TITLE
Live tinker: Css and Js

### ISSUE THREAD

**Issue by martinandersen3d** [erjanmx/laravel-live-tinker#5]
Really cool tool! 👍 

After installation, the route works. However, the CSS and JS files are not loaded.

Can you get them in / public / live-tinker somehow?

I guess I'm doing something wrong? Or do you have some kind of solution? Thanks :)

in the vendor\erjanmx\laravel-live-tinker\src\resources\views\index.blade.php

the css/js is refering to the /vendor/... folder..

![2018-10-02 01_18_59-window](https://user-images.githubusercontent.com/19984581/46320997-3ad2b100-c5e1-11e8-878c-45055c6e2266.png)

**Comment by erjanmx** [comment]
Hi, thanks.

Did you try to publish assets via the artisan command?

```
php artisan vendor:publish --provider=Erjanmx\\LiveTinker\\LiveTinkerServiceProvider --tag=public --force
```

**Comment by martinandersen3d** [comment]
yes i did try that (windows 10).

 The files does not get copied.

**Comment by martinandersen3d** [comment]
In this file:
https://github.com/erjanmx/laravel-live-tinker/blob/master/src/resources/views/index.blade.php

is the url reference for the CSS and JS correct? 


![2018-10-08 22_02_52-live-tinker](https://user-images.githubusercontent.com/19984581/46630914-10837500-cb46-11e8-826b-0c144959e6a0.png)

**Comment by erjanmx** [comment]
Those files are supposed to get copied into 
`public/vendor/live-tinker`

Do they exist in this location? Do you have some custom web-server configuration on serving static files?

**Comment by erjanmx** [comment]
@martinandersen3d , any news?

**Comment by martinandersen3d** [comment]
the files does not get copied, when i run the command from the commandline

`php artisan vendor:publish --provider=Erjanmx\\LiveTinker\\LiveTinkerServiceProvider --tag=public --force`

![image](https://user-images.githubusercontent.com/19984581/47966138-3cafea00-e04f-11e8-9964-6ca89ee8f7cf.png)

**Comment by martinandersen3d** [comment]
ok.. succes - it works now:

Follow these steps:
1- Add service provider to providers array on the config/app.php
2- Run php artisan config:cache
3- Run composer update
4- Run php artisan config:cache
5- Run php artisan vendor:publish

I'm on version Laravel Framework 5.5.44 - I did also add:
to configure by adding Service Provider in your /config/app.php

```
'providers' => [
    // other providers
    
    Erjanmx\LiveTinker\LiveTinkerServiceProvider::class,
 ],
```

**Comment by erjanmx** [comment]
Good, we can close this issue then?

**Comment by martinandersen3d** [comment]
yes

Den man. 5. nov. 2018 kl. 21.35 skrev Erjan Kalybek <
notifications@github.com>:
